# --- Cloudflare Pages Settings ---
# This is the directory Cloudflare Pages will deploy.
# It MUST exist after your build command runs.
pages_build_output_dir = "./cf_site_output"
name = "jesse-anderson-github-io"

# Configuration for the build process for Cloudflare Pages
[pages_build_config]
# This command:
# 1. Creates "./cf_site_output".
# 2. Copies your entire project root (".") into "./cf_site_output".
# 3. Excludes '.git', the output directory itself, and your large WASM file during the copy.
command = "mkdir ./cf_site_output && rsync -av --exclude='.git' --exclude='cf_site_output' --exclude='OP-Crime-Maps/js/duckdb/duckdb-eh.wasm' ./ ./cf_site_output/"

# --- General Wrangler Project Settings ---
# This is important for Wrangler to know how to interpret features.
compatibility_date = "2025-05-22" # Use your project's actual compatibility date

# The 'name' field is primarily for Wrangler CLI deployments of Workers.
# For Cloudflare Pages projects, the project name is set in the Cloudflare dashboard.
# It's generally safe to include it or omit it for Pages `wrangler.toml`.
# name = "jesse-anderson-portfolio" # Or your existing project name

# --- R2 Bucket Bindings ---
# Makes the R2 bucket available to server-side Cloudflare Functions (if you use them).
[[r2_buckets]]
binding = "ASSET_BUCKET"
bucket_name = "duckdb-assets"
preview_bucket_name = "duckdb-assets" # Often the same as bucket_name