# General Wrangler project settings
# This is important for feature compatibility.
compatibility_date = "2025-05-22" # Or your project's actual compatibility date

# Optional: You can specify the project name here, but using --project-name
# in the deploy command (as in your GitHub Action) is more explicit for CI.
# If present, ensure it matches your Cloudflare Pages project name.
name = "jesse-anderson-github-io"

# R2 Bucket Bindings
# These are relevant if you deploy Cloudflare Functions within your Pages project
# (e.g., in a 'functions' folder inside your 'dist' directory) that need to access R2.
# Client-side JavaScript (like your DuckDB WASM loader) accesses R2 via its public URL,
# not directly through this binding. This is also useful for `wrangler pages dev`.
[[r2_buckets]]
binding = "ASSET_BUCKET"
bucket_name = "duckdb-assets"
preview_bucket_name = "duckdb-assets" # Can be the same as bucket_name

# DO NOT INCLUDE:
# - [build] table
# - [pages_build_config] table
# - pages_build_output_dir key
# - pages_build_command key
#
# These are for Cloudflare's Git-integrated build system, which you are now bypassing.
# The GitHub Action handles the build and specifies the output directory directly
# to `wrangler pages deploy`.