name = "op-crime-maps"
compatibility_date = "2025-05-22"

# Tell Pages that the static assets live in OP-Crime-Maps/
pages_build_output_dir = "OP-Crime-Maps"

[[r2_buckets]]
binding = "ASSET_BUCKET"
bucket_name = "duckdb-assets"
preview_bucket_name = "duckdb-assets"
