project:
  type: website
  output-dir: _site
  resources:
  - "*.ipynb"

website:
  title: "Jesse Anderson's Blog"
  open-graph: true
  google-analytics: "G-5CSPYCMY55"
  cookie-consent: true
  navbar:
    right:
      - archive.qmd
      - about.qmd
      - icon: Folder symlink fill
        text: Portfolio
        href: https://jesse-anderson.github.io
      - icon: github
        href: https://github.com/jesse-anderson/
      - icon: linkedin
        href: https://www.linkedin.com/in/jesse-anderson-a7c5/


format:
  html:
    theme: cosmo
    css: styles.css
    grid:
      sidebar-width: 100px
      body-width: 1100px
      margin-width: 200px
      gutter-width: 1.5rem

# Ensure that code is always executed and not frozen
execute:
  freeze: false

