project:
  type: website
  output-dir: _site

website:
  title: "Jesse Anderson's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jesse-anderson/
      - icon: linkedin
        href: https://www.linkedin.com/in/jesse-anderson-a7c5/
format:
  html:
    theme: cosmo
    css: styles.css
    grid:
      sidebar-width: 100px
      body-width: 1100px
      margin-width: 200px
      gutter-width: 1.5rem



